apiVersion: apps/v1
kind: Deployment
metadata:
  name: lennartsapi
  labels:
    app: lennartsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name }}
  template:
    metadata:
      labels:
        app: {{.Values.name }}
    spec:
      containers:
        - name: {{.Values.name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
