apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lennartsapi
  namespace: lennartsapi
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: lennartsapi.ubk3s
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lennartsapi
            port:
              number: 80
